name: portfolio_web
description: A portfolio Webapp.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable:
  flutter_bloc:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/data/home_page.json
    - assets/data/about.json
    - assets/data/skills.json
    - assets/data/portfolio.json
    - assets/data/contact.json
